# Generated by Django 6.0.5 on 2026-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('SQL', 'SQL'), ('Django', 'Django'), ('Web', 'Web Development'), ('React', 'React'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('DSA', 'DSA'), ('Backend', 'Backend'), ('HR', 'HR')], max_length=100),
        ),
    ]
